#!/bin/bash
#
# Copyright (c) 2013 Mellanox Technologies. All rights reserved.
#
# This Software is licensed under one of the following licenses:
#
# 1) under the terms of the "Common Public License 1.0" a copy of which is
#    available from the Open Source Initiative, see
#    http://www.opensource.org/licenses/cpl.php.
#
# 2) under the terms of the "The BSD License" a copy of which is
#    available from the Open Source Initiative, see
#    http://www.opensource.org/licenses/bsd-license.php.
#
# 3) under the terms of the "GNU General Public License (GPL) Version 2" a
#    copy of which is available from the Open Source Initiative, see
#    http://www.opensource.org/licenses/gpl-license.php.
#
# Licensee has the right to choose one of the above licenses.
#
# Redistributions of source code must retain the above copyright
# notice and one of the license notices.
#
# Redistributions in binary form must reproduce both the above copyright
# notice, one of the license notices in the documentation
# and/or other materials provided with the distribution.
#
#

WDIR=${0%*/*}

usage()
{
cat << EOF

Usage: `basename $0` <kernel version> [options]

	Options:
		get-config:	Get configuration parameters for configure script
		get-modules:	Get a list of kernel modules that will be compiled
EOF
}


get-config()
{
def_configure_options=" \
	--with-core-mod \
	--with-user_mad-mod \
	--with-user_access-mod \
	--with-addr_trans-mod \
	--with-mlx4-mod \
	--with-mlx4_en-mod \
	--with-mlx5-mod \
	--with-ipoib-mod \
	--with-e_ipoib-mod \
	--with-srp-mod \
	--with-rds-mod \
	--with-iser-mod \
	"
# check if dkms.conf exists and parse it, otherwise use the env variable or the default
if [ -f $WDIR/../dkms.conf ];then
	options=
	while read line; do
		if [[ $line =~ BUILT_MODULE_NAME ]];then
			name=$(echo $line | sed -e 's/BUILT_MODULE_NAME\[[0-9]*\]=//g')
			flag=`module_to_flag $name`
			dashFlag=$(echo $flag | sed -e 's/-/\\\-/g')
			if ! (echo $options 2> /dev/null | grep "$dashFlag" >/dev/null 2>&1); then
				options="${options} $flag"
			fi
		fi
	done < $WDIR/../dkms.conf
	configure_options=$options
else
	configure_options=${configure_options:-"$def_configure_options"}
fi

echo $configure_options
}

module_to_flag()
{
	module=$1
	shift

	flag=

	case "$module" in
		compat|ib_core|ib_mad|ib_sa|ib_cm|iw_cm)
		flag=--with-core-mod
		;;
		ib_umad)
		flag=--with-user_mad-mod
		;;
		ib_uverbs|ib_ucm)
		flag=--with-user_access-mod
		;;
		ib_addr|rdma_cm|rdma_ucm)
		flag=--with-addr_trans-mod
		;;
		mlx4_core|mlx4_ib)
		flag=--with-mlx4-mod
		;;
		mlx5_core|mlx5_ib)
		flag=--with-mlx5-mod
		;;
		mlx4_en)
		flag=--with-mlx4_en-mod
		;;
		mlx4_ib)
		flag=--with-mlx4_ib-mod
		;;
		ib_ipoib)
		flag=--with-ipoib-mod
		;;
		eth_ipoib)
		flag=--with-e_ipoib-mod
		;;
		ib_srp)
		flag=--with-srp-mod
		;;
		scsi_transport_srp)
		flag=--with-srp-mod
		;;
		rds|rds_rdma|rds_tcp)
		flag=--with-rds-mod
		;;
		ib_iser)
		flag=--with-iser-mod
		;;
		memtrack)
		flag=--with-memtrack
		;;
		*)
		;;
	esac

	echo $flag
}

get-modules()
{
	modules=

	for opt in `get-config`
	do
		case "$opt" in
			--with-core-mod )
			modules="$modules \
				compat/compat \
				drivers/infiniband/core/ib_core \
				drivers/infiniband/core/ib_mad \
				drivers/infiniband/core/ib_sa \
				drivers/infiniband/core/ib_cm \
				drivers/infiniband/core/iw_cm"
			;;
			--with-user_mad-mod )
			modules="$modules \
				drivers/infiniband/core/ib_umad"
			;;
			--with-user_access-mod )
			modules="$modules \
				drivers/infiniband/core/ib_uverbs \
				drivers/infiniband/core/ib_ucm"
			;;
			--with-addr_trans-mod )
			modules="$modules \
				drivers/infiniband/core/ib_addr \
				drivers/infiniband/core/rdma_cm \
				drivers/infiniband/core/rdma_ucm"
			;;
			--with-mlx4-mod )
			modules="$modules \
				drivers/net/ethernet/mellanox/mlx4/mlx4_core \
				drivers/infiniband/hw/mlx4/mlx4_ib"
			;;
			--with-mlx5-mod )
			modules="$modules \
				drivers/net/ethernet/mellanox/mlx5/core/mlx5_core \
				drivers/infiniband/hw/mlx5/mlx5_ib"
			;;
			--with-mlx4_en-mod )
			modules="$modules \
				drivers/net/ethernet/mellanox/mlx4/mlx4_en"
			;;
			--with-mlx4_ib-mod )
			modules="$modules \
				drivers/infiniband/hw/mlx4/mlx4_ib"
			;;
			--with-ipoib-mod )
			modules="$modules \
				drivers/infiniband/ulp/ipoib/ib_ipoib"
			;;
			--with-e_ipoib-mod )
			modules="$modules \
				drivers/net/eipoib/eth_ipoib"
			;;
			--with-srp-mod )
			modules="$modules \
				drivers/infiniband/ulp/srp/ib_srp \
				drivers/scsi/scsi_transport_srp "
			;;
			--with-rds-mod )
			modules="$modules \
				net/rds/rds \
				net/rds/rds_rdma \
				net/rds/rds_tcp"
			;;
			--with-iser-mod )
			modules="$modules \
				drivers/infiniband/ulp/iser/ib_iser"
			;;
			--with-memtrack )
			modules="$modules \
				drivers/infiniband/debug/memtrack"
			;;
			*)
			;;
		esac
	done

	echo $modules
}

get-openib-conf()
{
	for opt in `get-config`
	do
		case "$opt" in
			--with-core-mod )
				echo
				echo "# Run sysctl performance tuning script"
				echo "RUN_SYSCTL=yes"
			;;
			--with-user_mad-mod )
			;;
			--with-user_access-mod )
				echo
				echo "# Load UCM module"
				echo "UCM_LOAD=yes"
			;;
			--with-addr_trans-mod )
				echo
				echo "# Load RDMA_CM module"
				echo "RDMA_CM_LOAD=yes"
				echo
				echo "# Load RDMA_UCM module"
				echo "RDMA_UCM_LOAD=yes"
				echo
				echo "# Increase ib_mad thread priority"
				echo "RENICE_IB_MAD=no"
			;;
			--with-mlx4-mod )
				echo
				echo "# Load MLX4 modules"
				echo "MLX4_LOAD=yes"
			;;
			--with-mlx4_en-mod )
				echo
				echo "# Load MLX4_EN module"
				echo "MLX4_EN_LOAD=yes"
			;;
			--with-mlx4_ib-mod )
			;;
			--with-mlx5-mod )
				echo
				echo "# Load MLX5 modules"
				echo "MLX5_LOAD=yes"
			;;
			--with-ipoib-mod )
				echo
				echo "# Load IPoIB"
				echo "IPOIB_LOAD=yes"
				echo
				echo "# Enable IPoIB Connected Mode"
				echo "SET_IPOIB_CM=auto"
			;;
			--with-e_ipoib-mod )
				echo
				echo "# Load E_IPoIB"
				echo "E_IPOIB_LOAD=no"
			;;
			--with-srp-mod )
				echo
				echo "# Load SRP module"
				echo "SRP_LOAD=no"
			;;
			--with-rds-mod )
				echo
				echo "# Load RDS module"
				echo "RDS_LOAD=no"
			;;
		esac
	done
}

kernelver=$1
shift

case "$1" in
	get-config)
	get-config
	;;
	get-modules)
	get-modules
	;;
	get-openib-conf)
	get-openib-conf
	;;
	-h|--help)
	usage
	exit 0
	;;
	*)
	usage
	exit 1
	;;
esac
